---
- hosts: all
  become: true
  tasks: 

- name: update package cache for CentOS
  dnf:
    name: epel-release
    state: latest
  when: ansible_distribution == "CentOS"

- name: Install Nagios on CentOS
  dnf: 
    name: 
      - nagios
      - nagios-plugins-all
  when: ansible_distribution == "CentOS"

- name: Ensure Nagios service is enabled and running on CentOS
  service:
    name: nagios
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"
